name: Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven (Force Stable API)
        run: |
          mvn -B package -DskipTests \
          -Dpaper.api.version=1.21.1-R0.1-SNAPSHOT
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: CoreProtect-Jar
          path: target/*.jar
